sudo: required

language: python
python: 
  - "3.6.1"
install: "pip install -r requirements.txt"

services:
  - docker

before_install:
-  docker-compose build

script:
  - docker-compose up -d
  - docker-compose run web ./event_microservice/manage.py makemigrations
  - docker-compose run web ./event_microservice/manage.py migrate
  - docker-compose run --workdir="/event_microservice/" web coverage run --source=. manage.py test
  - docker-compose run --workdir="/event_microservice/" web coverage report

after_success:
  - docker-compose run --workdir="/event_microservice/" web coveralls