sudo: required

language: python
python: 
  - "3.6.1"
install: "pip install -r requirements.txt"

services:
  - docker

before_install:
-  docker-compose build

script:
  - docker-compose up -d
  - docker-compose run -e TRAVIS_PULL_REQUEST=$TRAVIS_PULL_REQUEST -e TRAVIS="$TRAVIS" -e TRAVIS_JOB_ID="$TRAVIS_JOB_ID" -e TRAVIS_BRANCH="$TRAVIS_BRANCH" web ./event_microservice/manage.py makemigrations
  - docker-compose run -e TRAVIS_PULL_REQUEST=$TRAVIS_PULL_REQUEST -e TRAVIS="$TRAVIS" -e TRAVIS_JOB_ID="$TRAVIS_JOB_ID" -e TRAVIS_BRANCH="$TRAVIS_BRANCH" web ./event_microservice/manage.py migrate
  - docker-compose run -e TRAVIS_PULL_REQUEST=$TRAVIS_PULL_REQUEST -e TRAVIS="$TRAVIS" -e TRAVIS_JOB_ID="$TRAVIS_JOB_ID" -e TRAVIS_BRANCH="$TRAVIS_BRANCH" web bash -c "cd event_microservice/ && coverage run --source=. manage.py test"
  - docker-compose run -e TRAVIS_PULL_REQUEST=$TRAVIS_PULL_REQUEST -e TRAVIS="$TRAVIS" -e TRAVIS_JOB_ID="$TRAVIS_JOB_ID" -e TRAVIS_BRANCH="$TRAVIS_BRANCH" web bash -c "cd event_microservice/ && coverage report"

after_success:
  - docker-compose run -e TRAVIS_PULL_REQUEST=$TRAVIS_PULL_REQUEST -e TRAVIS="$TRAVIS" -e TRAVIS_JOB_ID="$TRAVIS_JOB_ID" -e TRAVIS_BRANCH="$TRAVIS_BRANCH" web bash -c "cd event_microservice/ && coveralls"